[package]
name = "window_clipboard_macos"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
objc = "0.2"
objc_id = "0.1"
objc-foundation = "0.1"
